//
// NoteModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct NoteModel: Codable, Identifiable, Equatable {

    public var id: Int?
    public var title: String?
    public var date: String?
    public var text: String?
    public var userId: Int?
    public var projectId: Int?

    public init(id: Int? = nil, title: String? = nil, date: String? = nil, text: String? = nil, userId: Int? = nil, projectId: Int? = nil) {
        self.id = id
        self.title = title
        self.date = date
        self.text = text
        self.userId = userId
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "id"
        case title
        case date
        case text
        case userId
        case projectId
    }
}

struct NoteItems {
    var demoRecentNoteList: [NoteModel] = [
        NoteModel(id: 1, title: "a bean", date: "Oct 11, 2020", text: "Here I come. To the butchers work...", userId: 1, projectId: 1),
        NoteModel(id: 2, title: "meeting note", date: "Oct 15, 2020", text: "Don't forget to buy cookies for the meeting", userId: 1, projectId: 1),
        NoteModel(id: 3, title: "siteminder 1", date: "Oct 17, 2020", text: "Make sure to let Anthony know that his rent is due this month", userId: 1, projectId: 1),
        NoteModel(id: 4, title: "Lord Bean", date: "Oct 9, 2020", text: "Hello? Is anyone else there?", userId: 1, projectId: 1),
        NoteModel(id: 5, title: "Lecture 4", date: "Oct 14, 2020", text: "Oops, wrong note", userId: 1, projectId: 1),
        NoteModel(id: 6, title: "Strike meeting", date: "Oct 20, 2020", text: "This next meeting will be very important", userId: 1, projectId: 1),
        NoteModel(id: 7, title: "alpha", date: "Oct 25, 2020", text: "I am your mother", userId: 1, projectId: 1),
        NoteModel(id: 8, title: "water note", date: "Oct 29, 2020", text: "Not today, Mr. Snack Boi. This stuff be mine and mine along for the taking of the booty", userId: 1, projectId: 1),
        NoteModel(id: 9, title: "Ninth note this month", date: "Oct 30, 2020", text: "This is the ninth note...", userId: 1, projectId: 1)
    ]
}
