//
// ProjectModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ProjectModel: Codable, Identifiable, Equatable {

    public var id: Int?
    public var name: String?
    public var userId: Int?

    public init(id: Int? = nil, name: String? = nil, userId: Int? = nil) {
        self.id = id
        self.name = name
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey {
        case id = "id"
        case name
        case userId
    }
}

struct ProjectItems {
    var demoProjectList: [ProjectModel] = [
        ProjectModel(id: 1, name: "Beans", userId: 1),
        ProjectModel(id: 2, name: "Minder", userId: 1),
        ProjectModel(id: 3, name: "Bender", userId: 1),
        ProjectModel(id: 4, name: "stell work", userId: 1),
        ProjectModel(id: 5, name: "meeting", userId: 1),
        ProjectModel(id: 6, name: "alpha strike", userId: 1),
        ProjectModel(id: 7, name: "Beans lord", userId: 1),
        ProjectModel(id: 8, name: "water", userId: 1),
    ]
}
